### ISSUE TITLE
CascStorageLib - error reading WDC3

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/CascStorageLib#1]
Getting error when trying to read spell.db2
![image](https://user-images.githubusercontent.com/45987426/50314304-61f19e00-04bf-11e9-8ee8-4c2f02d147eb.png)

[spell.db2.zip](https://github.com/Marlamin/WoWFormatTest/files/2700773/spell.db2.zip)

**Comment by Rokeo** [comment]
CASC 28807 retail

**Comment by Marlamin** [comment]
Let me know if it solves the problem

**Comment by Marlamin** [comment]
Gonna go ahead and close this, let me know if you're still having issues
